
export const HANDLE_PEOPLE_CHECKED = 'HANDLE_PEOPLE_CHECKED'
export const SHOW_MODAL = 'SHOW_MODAL'
export const DELETE_PEOPLE = 'DELETE_PEOPLE'
export const SELECT_PEOPLE = 'SELECT_PEOPLE'
export const ADD_NEW_PEOPLE = 'ADD_NEW_PEOPLE'